[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"
foreground = "#dadada"

[cursor.style]
blinking = "On"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.offset]
x = 0
y = 3

[window]
decorations = "Buttonless"
blur = true
opacity = 0.5
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 130
lines = 35

[window.padding]
x = 4
y = 4
