gui:
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: "delta --dark --paging=never --line-numbers"
update:
  method: never
disableStartupPopups: true
notARepository: skip
customCommands:
  - key: "W"
    context: "files"
    command: git commit --no-verify --no-edit --amend
    description: "Amend last commit without pre-commit hook"
