# ---- llm ----
model: ollama:deepseek-r1:8b

# ---- behavior ----
keybindings: vi
editor: nvim

# ---- clients ----
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    models:
      - name: deepseek-r1:8b
        max_input_tokens: 131072
      - name: qwen2.5-coder:7b
        max_input_tokens: 32768
